version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: inf24dw1g05/biblioteca-backend:latest  
    container_name: biblioteca_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - biblioteca_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: inf24dw1g05/biblioteca-frontend:latest  
    container_name: biblioteca_frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - biblioteca_network

networks:
  biblioteca_network:
    driver: bridge