version: '3.8'

services:
  api:
    image: biblioteca-api
    build:
      context: ./biblioteca-api-backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  admin:
    image: biblioteca-frontend
    build:
      context: ./biblioteca-admin-frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://api:3000/
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge