services:
  api:
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=biblioteca-database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1f18ac3cd637
      - DB_DATABASE=biblioteca_m3_recurso
    image: biblioteca-api
    build:
      context: ./biblioteca-api-backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  admin:
    image: biblioteca-frontend
    build:
      context: ./biblioteca-admin-frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://api:3000/
    networks:
      - app-network
    depends_on:
      - api

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: a045580/db-m3-biblioteca:latest
    container_name: biblioteca-database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1f18ac3cd637
      - MYSQL_DATABASE=biblioteca_m3_recurso
    volumes:
      - db-datasource:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1f18ac3cd637"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-datasource: